---

- name: backup old cert
  shell: |
    #!/bin/bash
    #
    
    # define old cert file name
    old_crt={{ old_crt }}
    old_key={{ old_key }}
    # define backup file name
    bk_crt={{ backup_crt }}
    bk_key={{ backup_key }}
    
    # backup old cert 
    if [ -e /etc/nginx/cert/${old_crt} ];then
      mv /etc/nginx/cert/{$old_crt,$bk_crt}
    fi
    if [ -e /etc/nginx/cert/server.key ];then
      mv /etc/nginx/cert/{$old_key,$bk_key}
    fi

- name: copy new cert file to dest host
  copy:
   src: "{{ item }}"
   dest: "/etc/nginx/cert/{{ item }}"
   owner: root
   group: root
   mode: 0644
  with_items: "{{ cert_files }}"
  notify:
  - restart nginx
